name: Deploy Angular to Vercel

on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Instalar dependências
        working-directory: portfolio
        run: npm install

      - name: Build Angular
        working-directory: portfolio
        run: npm run build --if-present

      - name: Instalar CLI do Vercel
        run: npm install -g vercel

      - name: Deploy para Vercel
        working-directory: portfolio
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
